services:
  postgres:
    image: postgres:16
    container_name: ums-postgres
    environment:
      POSTGRES_DB: ums
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
